modLoader="javafml"
loaderVersion="[40,)"
license="MIT"

[[mods]]
modId="dragonseeker"
version="${file.jarVersion}"
displayName="Dragonseeker"
credits="Ice & Fire was written by Alex-the-666. The textures for the items are based on Ice & Fire's Dragon Command Staff. Modified by KosmoMoustache"
authors="Syric. Modified by KosmoMoustache"
description='''
This mod adds tools with which to find dragons in the Ice & Fire mod.
Modified by KosmoMoustache.'''

[[dependencies.dragonseeker]]
    modId="forge"
    mandatory=true
    versionRange="[35,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.dragonseeker]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dragonseeker]]
    modId="iceandfire"
    mandatory=true
    versionRange="[2.1.12,)"
    ordering="AFTER"
    side="BOTH"
